/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidacaoRouteImport } from './routes/validacao'
import { Route as RiscoRouteImport } from './routes/risco'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OperacoesRouteImport } from './routes/operacoes'
import { Route as MercadosRouteImport } from './routes/mercados'
import { Route as LiveRouteImport } from './routes/live'
import { Route as IaRouteImport } from './routes/ia'
import { Route as EstrategiasRouteImport } from './routes/estrategias'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as BacktestsRouteImport } from './routes/backtests'
import { Route as IndexRouteImport } from './routes/index'

const ValidacaoRoute = ValidacaoRouteImport.update({
  id: '/validacao',
  path: '/validacao',
  getParentRoute: () => rootRouteImport,
} as any)
const RiscoRoute = RiscoRouteImport.update({
  id: '/risco',
  path: '/risco',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesRoute = OperacoesRouteImport.update({
  id: '/operacoes',
  path: '/operacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadosRoute = MercadosRouteImport.update({
  id: '/mercados',
  path: '/mercados',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const EstrategiasRoute = EstrategiasRouteImport.update({
  id: '/estrategias',
  path: '/estrategias',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestsRoute = BacktestsRouteImport.update({
  id: '/backtests',
  path: '/backtests',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtests': typeof BacktestsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/diario': typeof DiarioRoute
  '/estrategias': typeof EstrategiasRoute
  '/ia': typeof IaRoute
  '/live': typeof LiveRoute
  '/mercados': typeof MercadosRoute
  '/operacoes': typeof OperacoesRoute
  '/portfolio': typeof PortfolioRoute
  '/relatorios': typeof RelatoriosRoute
  '/resultados': typeof ResultadosRoute
  '/risco': typeof RiscoRoute
  '/validacao': typeof ValidacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtests': typeof BacktestsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/diario': typeof DiarioRoute
  '/estrategias': typeof EstrategiasRoute
  '/ia': typeof IaRoute
  '/live': typeof LiveRoute
  '/mercados': typeof MercadosRoute
  '/operacoes': typeof OperacoesRoute
  '/portfolio': typeof PortfolioRoute
  '/relatorios': typeof RelatoriosRoute
  '/resultados': typeof ResultadosRoute
  '/risco': typeof RiscoRoute
  '/validacao': typeof ValidacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtests': typeof BacktestsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/diario': typeof DiarioRoute
  '/estrategias': typeof EstrategiasRoute
  '/ia': typeof IaRoute
  '/live': typeof LiveRoute
  '/mercados': typeof MercadosRoute
  '/operacoes': typeof OperacoesRoute
  '/portfolio': typeof PortfolioRoute
  '/relatorios': typeof RelatoriosRoute
  '/resultados': typeof ResultadosRoute
  '/risco': typeof RiscoRoute
  '/validacao': typeof ValidacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtests'
    | '/configuracoes'
    | '/diario'
    | '/estrategias'
    | '/ia'
    | '/live'
    | '/mercados'
    | '/operacoes'
    | '/portfolio'
    | '/relatorios'
    | '/resultados'
    | '/risco'
    | '/validacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtests'
    | '/configuracoes'
    | '/diario'
    | '/estrategias'
    | '/ia'
    | '/live'
    | '/mercados'
    | '/operacoes'
    | '/portfolio'
    | '/relatorios'
    | '/resultados'
    | '/risco'
    | '/validacao'
  id:
    | '__root__'
    | '/'
    | '/backtests'
    | '/configuracoes'
    | '/diario'
    | '/estrategias'
    | '/ia'
    | '/live'
    | '/mercados'
    | '/operacoes'
    | '/portfolio'
    | '/relatorios'
    | '/resultados'
    | '/risco'
    | '/validacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestsRoute: typeof BacktestsRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DiarioRoute: typeof DiarioRoute
  EstrategiasRoute: typeof EstrategiasRoute
  IaRoute: typeof IaRoute
  LiveRoute: typeof LiveRoute
  MercadosRoute: typeof MercadosRoute
  OperacoesRoute: typeof OperacoesRoute
  PortfolioRoute: typeof PortfolioRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ResultadosRoute: typeof ResultadosRoute
  RiscoRoute: typeof RiscoRoute
  ValidacaoRoute: typeof ValidacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validacao': {
      id: '/validacao'
      path: '/validacao'
      fullPath: '/validacao'
      preLoaderRoute: typeof ValidacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risco': {
      id: '/risco'
      path: '/risco'
      fullPath: '/risco'
      preLoaderRoute: typeof RiscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes': {
      id: '/operacoes'
      path: '/operacoes'
      fullPath: '/operacoes'
      preLoaderRoute: typeof OperacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercados': {
      id: '/mercados'
      path: '/mercados'
      fullPath: '/mercados'
      preLoaderRoute: typeof MercadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrategias': {
      id: '/estrategias'
      path: '/estrategias'
      fullPath: '/estrategias'
      preLoaderRoute: typeof EstrategiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtests': {
      id: '/backtests'
      path: '/backtests'
      fullPath: '/backtests'
      preLoaderRoute: typeof BacktestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestsRoute: BacktestsRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DiarioRoute: DiarioRoute,
  EstrategiasRoute: EstrategiasRoute,
  IaRoute: IaRoute,
  LiveRoute: LiveRoute,
  MercadosRoute: MercadosRoute,
  OperacoesRoute: OperacoesRoute,
  PortfolioRoute: PortfolioRoute,
  RelatoriosRoute: RelatoriosRoute,
  ResultadosRoute: ResultadosRoute,
  RiscoRoute: RiscoRoute,
  ValidacaoRoute: ValidacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
